server:
  port: 8083

spring:
  application:
    name: discovery-service

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8083/eureka

logging:
  level:
    com.netflix.discovery: off
    com.netflix.eureka: off