server:
  port: ${SONG_SERVICE_PORT:8082}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://song-service-db:5432/song_db}
    username: ${SONG_DB_USER:postuser}
    password: ${SONG_DB_PASSWORD:paSS1word}
#    url: jdbc:postgresql://song-service-db:5432/song_db
#    username: postuser
#    password: paSS1word
#    driver-class-name: org.postgresql.Driver
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:${DISCOVERY_SERVICE_PORT:8083}/eureka/
  instance:
    prefer-ip-address: true