server:
  port: 8081

spring:
  application:
    name: resource-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/resource_db
    username: postuser
    password: paSS1word
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    enabled: false
    clean-disabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
song-service:
  name: song-service
  url: http://localhost:8082/songs

logging:
  level:
    org:
      springframework:
        beans:
          factory: DEBUG