server:
  port: ${RESOURCE_SERVICE_PORT:8081}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://resource-service-db:5432/resource_db}
    username: ${RESOURCE_DB_USER:postuser}
    password: ${RESOURCE_DB_PASSWORD:paSS1word}
song-service:
  name: song-service
  url: http://song-service:${SONG_SERVICE_PORT:8082}/songs

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:${DISCOVERY_SERVICE_PORT:8083}/eureka/
  instance:
    prefer-ip-address: true